version: "3"

services:

  mongodb:
    image: mongo:4-xenial
    ports:
      - 27017:27017
      - 27018:27018
      - 27019:27019
  
  redis:
    image: redis:4-alpine
    ports:
      - 6379:6379

  
  claro-api:
    build: ./claro
    container_name: claro-api
    ports:
      - 8081:8081
    depends_on:
      - mongodb
      - redis

  claro-front:
    build: ./claro-web
    container_name: claro-front
    ports:
      - 4200:4200
    environment:
      API_IP: claro-api
    depends_on:
      - claro-api